#PBS -l nodes=2
#PBS -l walltime=00:02:00
#PBS -j oe

cat $PBS_NODEFILE
NPROC=20
cd $PBS_O_WORKDIR
MPISIZE=$NPROC
MPIPROG=`basename $PBS_JOBNAME .pbs`
echo 'Running MPI program' $MPIPROG 'on' $MPISIZE 'processes'
echo 'Started at' `date`
echo '--------------------------------------------------------------------------------'
(time mpirun -n $MPISIZE ./$MPIPROG.o) 2>&1
echo '--------------------------------------------------------------------------------'
echo 'Finished at' `date`
